name: Push CI
run-name: "${{ github.actor }} ${{ github.ref_type }}/${{ github.ref_name }}"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v4

      - name: clone git repo
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'

      - name: run tests + race
        run: go test -race -v ./...

      - name: run vet
        run: go vet ./...

  deploy:
    runs-on: ubuntu-latest
    needs: ["test"]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.DOCKER_HUB_USER }}/hello-golang

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}